[project]
name = "crewai-job-hunter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[tools]>=0.193.0",
    "firecrawl-py>=4.3.6",
    "python-dotenv>=1.1.1",
]
